#組織データ管理(A) - 部門(AT010)
CREATE TABLE AT010(
     CDBUMON CHAR(5) NOT NULL COMMENT '部門ID',
     TXBUMON CHAR(30) NOT NULL COMMENT '部門名',
     NRKANRISYA CHAR(5) NOT NULL COMMENT '管理者№',
     TXTEKIYOU VARCHAR(300) COMMENT '摘要',
CONSTRAINT AT010_PK PRIMARY KEY (CDBUMON)
);

#組織データ管理(A) - 部門構成(AT011)
CREATE TABLE AT011(
     CDBUMON CHAR(5) NOT NULL COMMENT '部門ID',
     DTHAKKOUNENGETSU CHAR(6) NOT NULL COMMENT '発効年月',
     CDJYOUIBUMON CHAR(5) NOT NULL COMMENT '上位部門ID',
     DTSIKKOUNENGETSU CHAR(6) COMMENT '失効年月',
CONSTRAINT AT011_PK PRIMARY KEY (CDBUMON, DTHAKKOUNENGETSU),
CONSTRAINT AT011_FK1 FOREIGN KEY (CDJYOUIBUMON) REFERENCES AT010 (CDBUMON),
CONSTRAINT AT011_FK2 FOREIGN KEY (CDBUMON) REFERENCES AT010 (CDBUMON)
);

#組織データ管理(A) - 従業員(AT020)
CREATE TABLE AT020(
     NRJYUGYOIN CHAR(5) NOT NULL COMMENT '従業員№',
     TXKANA CHAR(30) NOT NULL COMMENT 'カナ名',
     TXKANJI CHAR(30) NOT NULL COMMENT '漢字名',
     KBKOYOU CHAR(5) NOT NULL COMMENT '雇用区分',
     DTNYUSYA DATE NOT NULL COMMENT '入社日',
     DTTAISYA DATE COMMENT '退社日',
CONSTRAINT AT020_PK PRIMARY KEY (NRJYUGYOIN)
);

#組織データ管理(A) - 従業員所属部門(AT021)
CREATE TABLE AT021(
     NRJYUGYOIN CHAR(5) NOT NULL COMMENT '従業員№',
     DTSYOZOKUNENGETSU CHAR(6) NOT NULL COMMENT '所属開始年月',
     CDBUMON CHAR(5) NOT NULL COMMENT '部門ID',
     DTLASTNENGETSU CHAR(6) NOT NULL COMMENT '所属最終年月',
     KBPRESENT CHAR(1) NOT NULL COMMENT '現行メンバー区分',
CONSTRAINT AT021_PK PRIMARY KEY (NRJYUGYOIN, DTSYOZOKUNENGETSU),
CONSTRAINT AT021_FK1 FOREIGN KEY (NRJYUGYOIN) REFERENCES AT020 (NRJYUGYOIN),
CONSTRAINT AT021_FK2 FOREIGN KEY (CDBUMON) REFERENCES AT010 (CDBUMON)
);

#受注データ管理(B) - 顧客(Customers)
CREATE TABLE Customers(
     code CHAR(20) NOT NULL COMMENT '顧客コード',
     name CHAR(30) NOT NULL COMMENT '顧客名',
     credit INTEGER NOT NULL COMMENT '与信限度額',
CONSTRAINT Customers_PK PRIMARY KEY (code)
);

#受注データ管理(B) - 受注見出し(Orders)
CREATE TABLE Orders(
     no CHAR(20) NOT NULL COMMENT '受注No',
     code CHAR(5) NOT NULL COMMENT '顧客コード',
     date DATE NOT NULL COMMENT '受注日',
CONSTRAINT Orders_PK PRIMARY KEY (no),
CONSTRAINT Orders_FK1 FOREIGN KEY (code) REFERENCES Customers (code)
);

#受注データ管理(B) - 受注明細(OrderDetails)
CREATE TABLE OrderDetails(
     orders_no CHAR(20) NOT NULL COMMENT '受注No',
     row_no CHAR(20) NOT NULL COMMENT '行番号',
     products_code CHAR(5) NOT NULL COMMENT '商品コード',
     quantity INTEGER NOT NULL COMMENT '受注数',
     ship_date DATE NOT NULL COMMENT '出荷日',
CONSTRAINT OrderDetails_PK PRIMARY KEY (orders_no, row_no),
CONSTRAINT OrderDetails_FK1 FOREIGN KEY (products_code) REFERENCES Products (code),
CONSTRAINT OrderDetails_FK2 FOREIGN KEY (orders_no) REFERENCES Orders (no)
);

#受注データ管理(B) - 商品(Products)
CREATE TABLE Products(
     id CHAR(10) NOT NULL COMMENT 'ID',
     code CHAR(5) NOT NULL COMMENT '商品コード',
     name CHAR(30) NOT NULL COMMENT '商品名',
     purchase_price INTEGER NOT NULL COMMENT '購入単価',
     sales_price INTEGER NOT NULL COMMENT '販売単価',
     unit CHAR(4) NOT NULL COMMENT '扱い単位',
CONSTRAINT Products_PK PRIMARY KEY (code)
);

#システム制御(Z) - システム変数(ZT010)
CREATE TABLE ZT010(
     IDVARIANT CHAR(20) NOT NULL COMMENT '変数ID',
     TXNAME CHAR(10) NOT NULL COMMENT '変数名',
     TXTYPE CHAR(10) NOT NULL COMMENT '変数値タイプ',
     TXVALUE CHAR(100) NOT NULL COMMENT '変数値',
     TXREMARKS VARCHAR(300) COMMENT '摘要',
CONSTRAINT ZT010_PK PRIMARY KEY (IDVARIANT)
);

#システム制御(Z) - ユーザ(ZT020)
CREATE TABLE ZT020(
     IDUSER CHAR(5) NOT NULL COMMENT 'ユーザID',
     TXNAME CHAR(30) NOT NULL COMMENT '漢字名',
     TXPASSWORD CHAR(50) NOT NULL COMMENT 'パスワード',
     DTVALID DATE NOT NULL COMMENT '発効日',
     DTEXPIRE DATE COMMENT '失効日',
     TXEMAIL CHAR(40) COMMENT 'メールアドレス',
     TXMENUS CHAR(30) NOT NULL COMMENT '利用可能メニュー',
     NREMPLOYEE CHAR(5) COMMENT '従業員№',
CONSTRAINT ZT020_PK PRIMARY KEY (IDUSER)
);

#システム制御(Z) - 採番テーブル(ZT030)
CREATE TABLE ZT030(
     IDNUMBER CHAR(20) NOT NULL COMMENT '番号ID',
     TXPREFIX CHAR(4) COMMENT '冒頭文字',
     NRNUMDIGIT SMALLINT NOT NULL COMMENT '数字桁数',
     NRCURRENT INTEGER COMMENT '番号現在値',
     FGWITHCD CHAR(1) NOT NULL COMMENT 'CD付加フラグ',
CONSTRAINT ZT030_PK PRIMARY KEY (IDNUMBER)
);

#システム制御(Z) - ユーザ定義区分(ZT040)
CREATE TABLE ZT040(
     IDUSERKUBUN CHAR(20) NOT NULL COMMENT 'ユーザ区分ID',
     KBUSERKUBUN CHAR(5) NOT NULL COMMENT 'ユーザ区分値',
     TXUSERKUBUN CHAR(20) NOT NULL COMMENT '区分値摘要',
     SQLIST SMALLINT NOT NULL COMMENT '一覧順序',
CONSTRAINT ZT040_PK PRIMARY KEY (IDUSERKUBUN, KBUSERKUBUN)
);

#システム制御(Z) - セッション(ZT050)
CREATE TABLE ZT050(
     NRSESSION CHAR(7) NOT NULL COMMENT 'セッション№',
     DTLOGIN TIMESTAMP NOT NULL COMMENT 'ログイン日時',
     DTLOGOUT TIMESTAMP COMMENT 'ログアウト日時',
     IDUSER CHAR(5) NOT NULL COMMENT 'ユーザID',
     TXIPADDRESS CHAR(20) NOT NULL COMMENT 'IPアドレス',
     VLVERSION CHAR(10) NOT NULL COMMENT '処理系バージョン',
     KBSESSIONSTATUS CHAR(2) COMMENT '状態',
CONSTRAINT ZT050_PK PRIMARY KEY (NRSESSION),
CONSTRAINT ZT050_FK1 FOREIGN KEY (IDUSER) REFERENCES ZT020 (IDUSER)
);

#システム制御(Z) - セッション明細(ZT051)
CREATE TABLE ZT051(
     NRSESSION CHAR(7) NOT NULL COMMENT 'セッション№',
     SQPROGRAM SMALLINT NOT NULL COMMENT 'PGM行番',
     IDMENU CHAR(2) NOT NULL COMMENT 'メニューID',
     IDPROGRAM CHAR(10) NOT NULL COMMENT 'プログラムID',
     TXPROGRAM CHAR(30) NOT NULL COMMENT '（プログラム名）',
     DTSTART TIMESTAMP NOT NULL COMMENT '利用開始日時',
     DTEND TIMESTAMP COMMENT '利用終了日時',
     KBPROGRAMSTATUS CHAR(2) COMMENT '終了状態コード',
     TXERRORLOG VARCHAR(300) COMMENT '処理ログ',
CONSTRAINT ZT051_PK PRIMARY KEY (NRSESSION, SQPROGRAM),
CONSTRAINT ZT051_FK1 FOREIGN KEY (NRSESSION) REFERENCES ZT050 (NRSESSION)
);

#システム制御(Z) - 消費税率(ZT060)
CREATE TABLE ZT060(
     DTSTART DATE NOT NULL COMMENT '税率開始日',
     KBKAZEI CHAR(1) NOT NULL COMMENT '課税区分',
     VLTAXRATE NUMERIC(3.2) NOT NULL COMMENT '消費税率',
CONSTRAINT ZT060_PK PRIMARY KEY (DTSTART, KBKAZEI)
);

#システム制御(Z) - 休日テーブル(ZT070)
CREATE TABLE ZT070(
     KBCALENDAR CHAR(2) NOT NULL COMMENT 'カレンダー区分',
     DTOFF DATE NOT NULL COMMENT '休日日付',
     TXOFF CHAR(20) COMMENT '摘要',
CONSTRAINT ZT070_PK PRIMARY KEY (KBCALENDAR, DTOFF)
);

#システム制御(Z) - 年次為替レート(ZT080)
CREATE TABLE ZT080(
     KBCURRENCY CHAR(3) NOT NULL COMMENT '通貨区分',
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     VLRATEB NUMERIC(10.3) NOT NULL COMMENT 'TTBレート',
     VLRATEM NUMERIC(10.3) NOT NULL COMMENT 'TTMレート',
     VLRATES NUMERIC(10.3) NOT NULL COMMENT 'TTSレート',
CONSTRAINT ZT080_PK PRIMARY KEY (KBCURRENCY, DTNEND)
);

#システム制御(Z) - 月次為替レート(ZT081)
CREATE TABLE ZT081(
     KBCURRENCY CHAR(3) NOT NULL COMMENT '通貨区分',
     DTNEND SMALLINT NOT NULL COMMENT '年度',
     DTMSEQ SMALLINT NOT NULL COMMENT '月度',
     VLRATEB NUMERIC(10.3) NOT NULL COMMENT 'TTBレート',
     VLRATEM NUMERIC(10.3) NOT NULL COMMENT 'TTMレート',
     VLRATES NUMERIC(10.3) NOT NULL COMMENT 'TTSレート',
CONSTRAINT ZT081_PK PRIMARY KEY (KBCURRENCY, DTNEND, DTMSEQ),
CONSTRAINT ZT081_FK1 FOREIGN KEY (KBCURRENCY, DTNEND) REFERENCES ZT080 (KBCURRENCY, DTNEND)
);

